set_property PACKAGE_PIN F22 [get_ports en]
set_property PACKAGE_PIN Y9 [get_ports iclk]
set_property PACKAGE_PIN U14 [get_ports oclk]
set_property IOSTANDARD LVCMOS18 [get_ports oclk]
set_property IOSTANDARD LVCMOS18 [get_ports iclk]
set_property IOSTANDARD LVCMOS18 [get_ports en]
